// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.devmedia.javamagazine.restfulapi.model.bean;

import br.com.devmedia.javamagazine.restfulapi.model.bean.Comentario;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Comentario_Roo_Configurable {
    
    declare @type: Comentario: @Configurable;
    
}
