// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.devmedia.javamagazine.rest.model.bean;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Permissao_Roo_Configurable {
    
    declare @type: Permissao: @Configurable;
    
}
